import { School, WorkPlanGoal, Project, TechnicalVisit, Formation, ScienceFair, TeamUser } from './types';

export const initialSchools: School[] = [
  {
    id: 's1',
    name: 'EEIEF Maria de Lourdes Cavalcante',
    neighborhood: 'Centro',
    infrastructureLevel: 'Bom',
    internetQuality: 'Boa',
    internetSpeedMbps: 50,
    equipmentCataloged: 24,
    equipmentRecovered: 18,
    equipmentDefective: 3,
    visitsCount: 3,
    lastVisitDate: '2026-05-14',
    needs: ['Substituição de 2 mouses', 'Manutenção preventiva nos estabilizadores'],
    recommendations: ['Utilizar laboratório em horários alternados para as turmas de EJA'],
    pendingActions: ['Troca de cabo de rede rompido'],
    status: 'atendida',
    inep: '23089104',
    servesInfant: true,
    servesElementary1: true,
    servesElementary2: false,
    directors: 'Diretora Antônia de Maria',
    coordinators: 'Coordenadora Francisca Gomes',
    desktopQty: 12,
    desktopWorkingQty: 10,
    notebookQty: 6,
    notebookWorkingQty: 4,
    tabletQty: 6,
    tabletWorkingQty: 4,
    internetProvider: 'Brisanet',
    internetAccessPoints: ['Laboratório de Informática', 'Secretaria Escolar'],
    totalStudents: 480,
    reportedDate: '25/07/2026'
  },
  {
    id: 's2',
    name: 'EEIEF Deputado Vilebaldo Martins',
    neighborhood: 'Venâncios',
    infrastructureLevel: 'Excelente',
    internetQuality: 'Excelente',
    internetSpeedMbps: 100,
    equipmentCataloged: 32,
    equipmentRecovered: 28,
    equipmentDefective: 1,
    visitsCount: 4,
    lastVisitDate: '2026-06-22',
    needs: ['Ampliação do sinal Wi-Fi para o pátio externo'],
    recommendations: ['Organizar oficina de robótica básica no contraturno'],
    pendingActions: [],
    status: 'atendida',
    inep: '23091234',
    servesInfant: false,
    servesElementary1: true,
    servesElementary2: true,
    directors: 'Diretor Roberto Cláudio',
    coordinators: 'Coordenadora Regina Duarte',
    desktopQty: 16,
    desktopWorkingQty: 14,
    notebookQty: 8,
    notebookWorkingQty: 8,
    tabletQty: 8,
    tabletWorkingQty: 6,
    internetProvider: 'Oi Fibra',
    internetAccessPoints: ['Biblioteca', 'Secretaria', 'Pátio Central'],
    totalStudents: 620,
    reportedDate: '26/07/2026'
  },
  {
    id: 's3',
    name: 'EEF Carlota Colares',
    neighborhood: 'São Vicente',
    infrastructureLevel: 'Aceitável',
    internetQuality: 'Instável',
    internetSpeedMbps: 20,
    equipmentCataloged: 15,
    equipmentRecovered: 10,
    equipmentDefective: 4,
    visitsCount: 2,
    lastVisitDate: '2026-04-10',
    needs: ['Upgrade de memória RAM nos computadores antigos', 'Nova fiação elétrica no laboratório'],
    recommendations: ['Solicitar suporte técnico da operadora de internet banda larga'],
    pendingActions: ['Substituir roteador principal', 'Reparar fiação elétrica'],
    status: 'atendida',
    inep: '23114502',
    servesInfant: true,
    servesElementary1: true,
    servesElementary2: true,
    directors: 'Diretor Pedro Bial',
    coordinators: 'Coordenador João Dória',
    desktopQty: 8,
    desktopWorkingQty: 5,
    notebookQty: 4,
    notebookWorkingQty: 3,
    tabletQty: 3,
    tabletWorkingQty: 2,
    internetProvider: 'Brisanet',
    internetAccessPoints: ['Sala dos Professores', 'Secretaria'],
    totalStudents: 310,
    reportedDate: '24/07/2026'
  },
  {
    id: 's4',
    name: 'EEF Maria José Bezerra',
    neighborhood: 'Cidade Nova',
    infrastructureLevel: 'Insuficiente',
    internetQuality: 'Ruim',
    internetSpeedMbps: 8,
    equipmentCataloged: 12,
    equipmentRecovered: 4,
    equipmentDefective: 6,
    visitsCount: 1,
    lastVisitDate: '2026-03-05',
    needs: ['Envio urgente de técnicos de hardware', 'Troca de fiação de rede interna', 'Aumento de velocidade contratada'],
    recommendations: ['Limpeza completa de poeira das máquinas desativadas', 'Utilização offline temporária de softwares educativos'],
    pendingActions: ['Instalação de novo rack de rede', 'Recuperação de 6 computadores travados'],
    status: 'atendida',
    inep: '23004561',
    servesInfant: false,
    servesElementary1: true,
    servesElementary2: true,
    directors: 'Diretora Maria Lúcia',
    coordinators: 'Coordenadora Amanda Lima',
    desktopQty: 6,
    desktopWorkingQty: 2,
    notebookQty: 4,
    notebookWorkingQty: 1,
    tabletQty: 2,
    tabletWorkingQty: 1,
    internetProvider: 'Telemar / Oi',
    internetAccessPoints: ['Secretaria'],
    totalStudents: 220,
    reportedDate: '22/07/2026'
  },
  {
    id: 's5',
    name: 'EEIEF Antônia de Souza Martins',
    neighborhood: 'Fátima',
    infrastructureLevel: 'Bom',
    internetQuality: 'Boa',
    internetSpeedMbps: 40,
    equipmentCataloged: 18,
    equipmentRecovered: 15,
    equipmentDefective: 2,
    visitsCount: 2,
    lastVisitDate: '2026-06-18',
    needs: ['Ajuste na altura das bancadas de informática'],
    recommendations: ['Capacitar o monitor da escola para realizar resets básicos de modem'],
    pendingActions: [],
    status: 'atendida',
    inep: '23214567',
    servesInfant: true,
    servesElementary1: true,
    servesElementary2: false,
    directors: 'Diretora Antônia Martins Filho',
    coordinators: 'Coordenador Raimundo Nonato',
    desktopQty: 8,
    desktopWorkingQty: 7,
    notebookQty: 5,
    notebookWorkingQty: 4,
    tabletQty: 5,
    tabletWorkingQty: 4,
    internetProvider: 'Multiplay',
    internetAccessPoints: ['Diretoria', 'Laboratório'],
    totalStudents: 390,
    reportedDate: '26/07/2026'
  },
  {
    id: 's6',
    name: 'EEF José Freire de Pinho',
    neighborhood: 'Altos',
    infrastructureLevel: 'Aceitável',
    internetQuality: 'Instável',
    internetSpeedMbps: 15,
    equipmentCataloged: 14,
    equipmentRecovered: 8,
    equipmentDefective: 5,
    visitsCount: 0,
    needs: ['Reestruturação total do laboratório de informática', 'Configuração de proxy de segurança'],
    recommendations: ['Vistoria inicial e elaboração de laudo técnico de infraestrutura'],
    pendingActions: ['Visita técnica para diagnóstico geral', 'Levantamento físico do inventário'],
    status: 'pendente',
    inep: '23114589',
    servesInfant: false,
    servesElementary1: true,
    servesElementary2: true,
    directors: 'Diretor José Alencar',
    coordinators: 'Coordenadora Letícia Bezerra',
    desktopQty: 6,
    desktopWorkingQty: 3,
    notebookQty: 4,
    notebookWorkingQty: 3,
    tabletQty: 4,
    tabletWorkingQty: 2,
    internetProvider: 'Brisanet',
    internetAccessPoints: ['Secretaria', 'Laboratório'],
    totalStudents: 275,
    reportedDate: '23/07/2026'
  },
  {
    id: 's7',
    name: 'EEF Joaquim de Souza Resende',
    neighborhood: 'Ilha',
    infrastructureLevel: 'Excelente',
    internetQuality: 'Excelente',
    internetSpeedMbps: 120,
    equipmentCataloged: 28,
    equipmentRecovered: 26,
    equipmentDefective: 0,
    visitsCount: 3,
    lastVisitDate: '2026-05-30',
    needs: [],
    recommendations: ['Utilizar a escola como piloto para a implantação de Chromebooks em 2027'],
    pendingActions: [],
    status: 'atendida',
    inep: '23098765',
    servesInfant: false,
    servesElementary1: true,
    servesElementary2: true,
    directors: 'Diretora Carla Diaz',
    coordinators: 'Coordenador Tiago Leifert',
    desktopQty: 12,
    desktopWorkingQty: 11,
    notebookQty: 8,
    notebookWorkingQty: 8,
    tabletQty: 8,
    tabletWorkingQty: 7,
    internetProvider: 'Oi Fibra',
    internetAccessPoints: ['Laboratório', 'Sala de Leitura', 'Diretoria'],
    totalStudents: 540,
    reportedDate: '26/07/2026'
  },
  {
    id: 's8',
    name: 'EEF Francisco de Assis de Souza',
    neighborhood: 'Planaltina',
    infrastructureLevel: 'Insuficiente',
    internetQuality: 'Sem Conexão',
    internetSpeedMbps: 0,
    equipmentCataloged: 8,
    equipmentRecovered: 2,
    equipmentDefective: 5,
    visitsCount: 0,
    needs: ['Instalação física de cabeamento externo', 'Fornecimento de roteador Wi-Fi', 'Descarte correto de lixo eletrônico'],
    recommendations: ['Oficiar a empresa provedora responsável pelo sinal governamental na localidade'],
    pendingActions: ['Instalar internet banda larga', 'Reativar laboratório'],
    status: 'pendente',
    inep: '23223344',
    servesInfant: true,
    servesElementary1: true,
    servesElementary2: false,
    directors: 'Diretor Reginaldo Rossi',
    coordinators: 'Coordenadora Rita Lee',
    desktopQty: 4,
    desktopWorkingQty: 1,
    notebookQty: 2,
    notebookWorkingQty: 1,
    tabletQty: 2,
    tabletWorkingQty: 0,
    internetProvider: 'Nenhum (Sem Conexão)',
    internetAccessPoints: [],
    totalStudents: 150,
    reportedDate: '20/07/2026'
  }
];

export const initialGoals: WorkPlanGoal[] = [
  {
    id: 'g1',
    title: 'Modernização da Infraestrutura Tecnológica das Escolas',
    targetValue: 8,
    currentValue: 6,
    unit: 'Escolas Reestruturadas',
    startDate: '2026-01-10',
    dueDate: '2026-11-30',
    status: 'em_andamento',
    category: 'Infraestrutura',
    description: 'Promover a manutenção corretiva, instalação de computadores recuperados e adequação elétrica dos laboratórios de informática.',
    actions: [
      {
        id: 'a1_1',
        goalId: 'g1',
        title: 'Inventariar e diagnosticar laboratórios das 8 escolas municipais',
        completionPercent: 100,
        startDate: '2026-01-15',
        dueDate: '2026-03-31',
        status: 'concluido',
        category: 'Infraestrutura',
        microactionsCount: 8,
        microactionsCompleted: 8,
        responsible: 'Técnico Reginaldo',
        impactScore: 8
      },
      {
        id: 'a1_2',
        goalId: 'g1',
        title: 'Recuperação e formatação de computadores defeituosos/antigos',
        completionPercent: 85,
        startDate: '2026-02-10',
        dueDate: '2026-08-30',
        status: 'em_andamento',
        category: 'Infraestrutura',
        microactionsCount: 40,
        microactionsCompleted: 34,
        responsible: 'Técnico Reginaldo',
        impactScore: 9
      },
      {
        id: 'a1_3',
        goalId: 'g1',
        title: 'Adequação de rede elétrica e lógica em laboratórios críticos',
        completionPercent: 40,
        startDate: '2026-04-01',
        dueDate: '2026-06-30',
        status: 'atrasado', // Fim em junho, incompleto!
        category: 'Infraestrutura',
        microactionsCount: 5,
        microactionsCompleted: 2,
        responsible: 'Equipe de Manutenção',
        impactScore: 7
      }
    ]
  },
  {
    id: 'g2',
    title: 'Universalização da Conectividade Escolar de Alta Velocidade',
    targetValue: 8,
    currentValue: 7,
    unit: 'Escolas Conectadas (>20Mbps)',
    startDate: '2026-02-01',
    dueDate: '2026-10-15',
    status: 'em_andamento',
    category: 'Conectividade',
    description: 'Instalar e monitorar links de internet de alta velocidade com cobertura interna estável por meio de roteadores de qualidade empresarial.',
    actions: [
      {
        id: 'a2_1',
        goalId: 'g2',
        title: 'Contratação e upgrade de link de internet de fibra óptica',
        completionPercent: 100,
        startDate: '2026-02-15',
        dueDate: '2026-05-15',
        status: 'concluido',
        category: 'Conectividade',
        microactionsCount: 3,
        microactionsCompleted: 3,
        responsible: 'Gestão de Licitação',
        impactScore: 10
      },
      {
        id: 'a2_2',
        goalId: 'g2',
        title: 'Instalação de access points para cobertura Wi-Fi institucional',
        completionPercent: 65,
        startDate: '2026-05-01',
        dueDate: '2026-09-30',
        status: 'em_andamento',
        category: 'Conectividade',
        microactionsCount: 8,
        microactionsCompleted: 5,
        responsible: 'Equipe de Rede',
        impactScore: 8
      }
    ]
  },
  {
    id: 'g3',
    title: 'Capacitação Docente em Tecnologias e Culturas Digitais',
    targetValue: 120,
    currentValue: 95,
    unit: 'Professores Formados',
    startDate: '2026-02-10',
    dueDate: '2026-11-15',
    status: 'em_andamento',
    category: 'Formação',
    description: 'Oferecer oficinas práticas de recursos educacionais abertos, Google Workspace, inteligência artificial pedagógica e robótica educacional.',
    actions: [
      {
        id: 'a3_1',
        goalId: 'g3',
        title: 'Realização de Formações do 1º Semestre (Fundamentos Digitais)',
        completionPercent: 100,
        startDate: '2026-02-20',
        dueDate: '2026-06-25',
        status: 'concluido',
        category: 'Formação',
        microactionsCount: 4,
        microactionsCompleted: 4,
        responsible: 'Coordenador Pedagógico',
        impactScore: 9
      },
      {
        id: 'a3_2',
        goalId: 'g3',
        title: 'Oficinas Avançadas (I.A. em Sala de Aula e Gamificação)',
        completionPercent: 15,
        startDate: '2026-07-01',
        dueDate: '2026-10-20',
        status: 'em_andamento',
        category: 'Formação',
        microactionsCount: 6,
        microactionsCompleted: 1,
        responsible: 'Formadora Letícia',
        impactScore: 9
      }
    ]
  },
  {
    id: 'g4',
    title: 'Promoção da Inovação Científica via Feiras de Ciências Escolares',
    targetValue: 8,
    currentValue: 4,
    unit: 'Feiras Realizadas',
    startDate: '2026-03-01',
    dueDate: '2026-12-10',
    status: 'em_andamento',
    category: 'Inovação Científica',
    description: 'Fomentar feiras internas de ciências em todas as escolas da rede municipal, culminando na Feira Municipal de Crateús.',
    actions: [
      {
        id: 'a4_1',
        goalId: 'g4',
        title: 'Elaboração e publicação do Edital da Feira de Ciências',
        completionPercent: 100,
        startDate: '2026-03-10',
        dueDate: '2026-04-15',
        status: 'concluido',
        category: 'Inovação Científica',
        microactionsCount: 1,
        microactionsCompleted: 1,
        responsible: 'Comissão Científica',
        impactScore: 8
      },
      {
        id: 'a4_2',
        goalId: 'g4',
        title: 'Oficinas de Metodologia Científica para Professores Orientadores',
        completionPercent: 100,
        startDate: '2026-04-20',
        dueDate: '2026-06-15',
        status: 'concluido',
        category: 'Inovação Científica',
        microactionsCount: 3,
        microactionsCompleted: 3,
        responsible: 'Prof. Gilberto',
        impactScore: 7
      },
      {
        id: 'a4_3',
        goalId: 'g4',
        title: 'Apoio logístico para feiras escolares do 1º lote',
        completionPercent: 100,
        startDate: '2026-05-01',
        dueDate: '2026-06-30',
        status: 'concluido',
        category: 'Inovação Científica',
        microactionsCount: 4,
        microactionsCompleted: 4,
        responsible: 'Comissão Organizadora',
        impactScore: 8
      },
      {
        id: 'a4_4',
        goalId: 'g4',
        title: 'Realização das feiras escolares do 2º lote',
        completionPercent: 0,
        startDate: '2026-08-01',
        dueDate: '2026-10-31',
        status: 'nao_iniciado',
        category: 'Inovação Científica',
        microactionsCount: 4,
        microactionsCompleted: 0,
        responsible: 'Comissão Organizadora',
        impactScore: 9
      }
    ]
  },
  {
    id: 'g5',
    title: 'Implantação de Robótica Educacional com Sucata Eletrônica',
    targetValue: 5,
    currentValue: 0,
    unit: 'Oficinas Implementadas',
    startDate: '2026-05-10',
    dueDate: '2026-11-20',
    status: 'nao_iniciado',
    category: 'Cultura Maker',
    description: 'Instaurar oficinas de montagem e programação básica a partir de lixo eletrônico recuperado nas visitas técnicas.',
    actions: [
      {
        id: 'a5_1',
        goalId: 'g5',
        title: 'Definição das diretrizes pedagógicas e kits alternativos',
        completionPercent: 10,
        startDate: '2026-06-01',
        dueDate: '2026-07-30',
        status: 'em_andamento',
        category: 'Cultura Maker',
        microactionsCount: 4,
        microactionsCompleted: 1,
        responsible: 'Formadora Letícia',
        impactScore: 6
      }
    ]
  },
  {
    id: 'g6',
    title: 'Agendas Pedagógicas',
    targetValue: 8,
    currentValue: 5,
    unit: 'Escolas Acompanhadas',
    startDate: '2026-02-01',
    dueDate: '2026-11-30',
    status: 'em_andamento',
    category: 'Agendas Pedagógicas',
    description: 'Acompanhamento, planejamento e alinhamento do cronograma de práticas pedagógicas e uso de recursos digitais nas escolas.',
    actions: [
      {
        id: 'a6_1',
        goalId: 'g6',
        title: 'Acompanhamento e alinhamento do planejamento pedagógico digital',
        completionPercent: 60,
        startDate: '2026-02-15',
        dueDate: '2026-11-15',
        status: 'em_andamento',
        category: 'Agendas Pedagógicas',
        microactionsCount: 8,
        microactionsCompleted: 5,
        responsible: 'Equipe Pedagógica / CICD',
        impactScore: 8
      }
    ]
  }
];

export const initialProjects: Project[] = [
  {
    id: 'p1',
    name: 'Projeto Crateús Conectado e Digital',
    startDate: '2026-01-15',
    dueDate: '2026-11-15',
    status: 'ativo',
    completionPercent: 72,
    budget: 45000,
    budgetSpent: 32400,
    responsible: 'Coord. Antonio Janeison Rodrigues Maia',
    results: ['6 escolas com internet de alta velocidade instalada', '88 professores formados no uso pedagógico básico'],
    description: 'Implantação de infraestrutura e formação para viabilizar as culturas digitais em larga escala no município de Crateús.',
    schoolsInvolved: ['s1', 's2', 's3', 's4', 's5', 's7']
  },
  {
    id: 'p2',
    name: 'Inova Escola - Laboratórios Verdes e Reciclagem Tech',
    startDate: '2026-02-10',
    dueDate: '2026-06-30',
    status: 'finalizado', // Concluído!
    completionPercent: 100,
    budget: 15000,
    budgetSpent: 14850,
    responsible: 'Prof. Gilberto / Reginaldo',
    results: ['81 computadores recuperados e devolvidos aos laboratórios', 'Criação de 3 oficinas permanentes de robótica de baixo custo'],
    description: 'Mutirão de recolhimento de computadores queimados e peças obsoletas para remanufatura e distribuição em laboratórios escolares.',
    schoolsInvolved: ['s1', 's3', 's4', 's5']
  },
  {
    id: 'p3',
    name: 'Feira Municipal de Ciências e Tecnologias de Crateús - FEMCITE',
    startDate: '2026-03-01',
    dueDate: '2026-12-15',
    status: 'ativo',
    completionPercent: 45,
    budget: 30000,
    budgetSpent: 12000,
    responsible: 'Comissão Pedagógica',
    results: ['Edital publicado', 'Oficinas metodológicas de ciências concluídas para 42 orientadores'],
    description: 'Planejamento e realização das etapas escolares e final municipal de exposição científica educacional das escolas de Crateús.',
    schoolsInvolved: ['s1', 's2', 's3', 's4', 's5', 's6', 's7', 's8']
  },
  {
    id: 'p4',
    name: 'Inclusão Digital Cidadã (Cultura Maker nas Escolas do Campo)',
    startDate: '2026-08-01',
    dueDate: '2026-12-10',
    status: 'pendente',
    completionPercent: 0,
    budget: 20000,
    budgetSpent: 0,
    responsible: 'Dra. Letícia Bezerra',
    results: [],
    description: 'Desenvolvimento de caravanas tecnológicas para atender às escolas rurais do município com laboratórios itinerantes e oficinas curtas.',
    schoolsInvolved: ['s6', 's8']
  }
];

export const initialVisits: TechnicalVisit[] = [
  {
    id: 'v1',
    schoolId: 's4',
    schoolName: 'EEF Maria José Bezerra',
    date: '2026-03-05',
    responsible: 'Téc. Reginaldo Santos',
    details: 'Vistoria inicial. Encontrados 6 computadores travados por malware e fonte queimada. Internet municipal oscilando entre 2 e 8 Mbps.',
    internetSpeed: 8,
    mainNeeds: ['Novas fontes para computadores', 'Link de internet dedicado'],
    status: 'realizada',
    photos: ['https://images.unsplash.com/photo-1581092921461-eab62e97a780?auto=format&fit=crop&q=80&w=400']
  },
  {
    id: 'v2',
    schoolId: 's3',
    schoolName: 'EEF Carlota Colares',
    date: '2026-04-10',
    responsible: 'Téc. Reginaldo Santos',
    details: 'Manutenção corretiva em 5 terminais. Verificadas instalações elétricas antigas que geram quedas de disjuntor quando o ar condicionado liga junto às máquinas.',
    internetSpeed: 20,
    mainNeeds: ['Readequação elétrica externa', 'Ampliação Wi-Fi'],
    status: 'realizada',
    photos: ['https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=400']
  },
  {
    id: 'v3',
    schoolId: 's1',
    schoolName: 'EEIEF Maria de Lourdes Cavalcante',
    date: '2026-05-14',
    responsible: 'Coord. Antonio Janeison Rodrigues Maia',
    details: 'Entrega de 5 computadores restaurados do Inova Escola. O laboratório agora conta com 15 computadores ativos.',
    internetSpeed: 50,
    mainNeeds: ['Troca de cabo rompido', 'Manutenção preventiva'],
    status: 'realizada',
    photos: ['https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?auto=format&fit=crop&q=80&w=400']
  },
  {
    id: 'v4',
    schoolId: 's2',
    schoolName: 'EEIEF Deputado Vilebaldo Martins',
    date: '2026-06-22',
    responsible: 'Téc. Reginaldo / Gilberto',
    details: 'Atendimento preventivo e suporte à rede interna. Velocidade excelente de 100 Mbps em fibra óptica. Todas as máquinas estão em pleno funcionamento.',
    internetSpeed: 100,
    mainNeeds: ['Roteador adicional externa'],
    status: 'realizada',
    photos: ['https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=400']
  },
  {
    id: 'v5',
    schoolId: 's6',
    schoolName: 'EEF José Freire de Pinho',
    date: '2026-07-15',
    responsible: 'Téc. Reginaldo Santos',
    details: 'Agendamento de visita de diagnóstico básico e primeiro inventário físico de informática.',
    internetSpeed: 0,
    mainNeeds: ['Definição de cronograma de implantação', 'Recuperação de rede local'],
    status: 'pendente',
    photos: []
  },
  {
    id: 'v6',
    schoolId: 's8',
    schoolName: 'EEF Francisco de Assis de Souza',
    date: '2026-07-22',
    responsible: 'Coord. Antonio Janeison Rodrigues Maia',
    details: 'Visita técnica de alta prioridade para verificar a viabilidade física de instalação de conexão de fibra óptica rural.',
    internetSpeed: 0,
    mainNeeds: ['Instalação física de postes e fibras', 'Estruturação de fiação elétrica'],
    status: 'pendente',
    photos: []
  }
];

export const initialFormations: Formation[] = [
  {
    id: 'f1',
    title: 'Descomplicando as Tecnologias na Prática Pedagógica',
    date: '2026-03-12',
    theme: 'Recursos Educacionais e Google Workspace',
    audience: 'Professores do Fundamental I',
    participantsCount: 45,
    status: 'realizada',
    hours: 8
  },
  {
    id: 'f2',
    title: 'Robótica Criativa e Sucata Eletrônica no Currículo',
    date: '2026-04-28',
    theme: 'Cultura Maker e Inovação Científica',
    audience: 'Professores do Fundamental II',
    participantsCount: 38,
    status: 'realizada',
    hours: 12
  },
  {
    id: 'f3',
    title: 'Inteligência Artificial Generativa para Planejamento Escolar',
    date: '2026-06-15',
    theme: 'Planejamento e Automação de Materiais com I.A.',
    audience: 'Gestores de Escolas e Coordenadores Pedagógicos',
    participantsCount: 32,
    status: 'realizada',
    hours: 4
  },
  {
    id: 'f4',
    title: 'Oficina Avançada: Gamificação e Metodologias Ativas',
    date: '2026-08-14',
    theme: 'Gamificação e Aprendizagem Baseada em Problemas',
    audience: 'Professores Orientadores',
    participantsCount: 40,
    status: 'planejada',
    hours: 16
  }
];

export const initialFairs: ScienceFair[] = [
  {
    id: 'fr1',
    name: 'I Feira de Inovação Científica da Maria de Lourdes',
    schoolId: 's1',
    schoolName: 'EEIEF Maria de Lourdes Cavalcante',
    date: '2026-05-25',
    projectsCount: 12,
    status: 'realizada'
  },
  {
    id: 'fr2',
    name: 'Feira Tecnológica Escolar Vilebaldo Martins',
    schoolId: 's2',
    schoolName: 'EEIEF Deputado Vilebaldo Martins',
    date: '2026-06-03',
    projectsCount: 16,
    status: 'realizada'
  },
  {
    id: 'fr3',
    name: 'Mostra Científica de Carlota Colares',
    schoolId: 's3',
    schoolName: 'EEF Carlota Colares',
    date: '2026-06-12',
    projectsCount: 8,
    status: 'realizada'
  },
  {
    id: 'fr4',
    name: 'Semana de Robótica e Ciências da Maria José Bezerra',
    schoolId: 's4',
    schoolName: 'EEF Maria José Bezerra',
    date: '2026-06-25',
    projectsCount: 11,
    status: 'realizada'
  },
  {
    id: 'fr5',
    name: 'X Mostra de Ciências de Joaquim Resende',
    schoolId: 's7',
    schoolName: 'EEF Joaquim de Souza Resende',
    date: '2026-08-20',
    projectsCount: 14,
    status: 'planejada'
  },
  {
    id: 'fr6',
    name: 'Feira Científica da Antônia Martins',
    schoolId: 's5',
    schoolName: 'EEIEF Antônia de Souza Martins',
    date: '2026-09-04',
    projectsCount: 10,
    status: 'planejada'
  }
];

export const initialTeamUsers: TeamUser[] = [
  {
    id: 'usr_admin_1',
    name: 'Prof. Francisco Reginaldo',
    roleTitle: 'Coordenador de Inovação e Culturas Digitais (Administrador)',
    email: 'coordenadoria.inovacao@crateus.ce.gov.br',
    phone: '(88) 99876-5432',
    password: 'Crateus@123',
    role: 'administrador',
    status: 'ativo',
    allowedTabs: ['dashboard', 'timeline', 'pending', 'achieved', 'reports', 'manage'],
    allowedSubTabs: ['actions', 'projects', 'visits', 'formations', 'fairs', 'new-goal', 'schools', 'users', 'coordenadoria', 'cloud-sync'],
    notes: 'Administrador Geral responsável pela Coordenadoria de Inovação e Culturas Digitais.',
    createdAt: '2026-01-10'
  },
  {
    id: 'usr_member_1',
    name: 'Téc. Reginaldo Santos',
    roleTitle: 'Técnico de Suporte e Conectividade',
    email: 'reginaldo.suporte@crateus.ce.gov.br',
    phone: '(88) 99123-4567',
    password: 'Crateus@123',
    role: 'membro',
    status: 'ativo',
    allowedTabs: ['dashboard', 'pending', 'manage'],
    allowedSubTabs: ['actions', 'visits', 'schools'],
    assignedGoalIds: ['g1', 'g2'],
    assignedActionIds: ['a1_1', 'a1_2', 'a2_1'],
    notes: 'Responsável pelas rotas de manutenção, visitas técnicas e infraestrutura Wi-Fi das escolas.',
    createdAt: '2026-02-01'
  },
  {
    id: 'usr_member_2',
    name: 'Profa. Maria Clara Medeiros',
    roleTitle: 'Assessora Pedagógica de T.I.C.',
    email: 'mariaclara.pedagogico@crateus.ce.gov.br',
    phone: '(88) 98877-6655',
    password: 'Crateus@123',
    role: 'membro',
    status: 'ativo',
    allowedTabs: ['dashboard', 'timeline', 'reports', 'manage'],
    allowedSubTabs: ['actions', 'formations', 'fairs'],
    assignedGoalIds: ['g3', 'g4'],
    assignedActionIds: ['a3_1', 'a4_1'],
    notes: 'Responsável pelas formações de professores, projetos pedagógicos e feiras de ciências.',
    createdAt: '2026-02-15'
  },
  {
    id: 'usr_member_3',
    name: 'Eng. Carlos Eduardo Viana',
    roleTitle: 'Analista de Infraestrutura e Redes',
    email: 'carloseduardo.redes@crateus.ce.gov.br',
    phone: '(88) 99765-4321',
    password: 'Crateus@123',
    role: 'membro',
    status: 'ativo',
    allowedTabs: ['dashboard', 'pending', 'manage'],
    allowedSubTabs: ['actions', 'projects', 'visits'],
    assignedGoalIds: ['g2'],
    assignedActionIds: ['a2_2'],
    notes: 'Especialista em links de alta velocidade, fibra óptica e inventário de hardware.',
    createdAt: '2026-03-01'
  }
];
